// const reporter = require('cucumber-html-reporter');

// const options = {
//   theme: 'bootstrap',
//   jsonFile: 'cucumber_report.json',  // this file will be generated by Cucumber
//   output: 'cucumber_report.html',    // your HTML report
//   reportSuiteAsScenarios: true,
//   launchReport: true,
//   metadata: {
//     "App Version":"1.0.0",
//     "Browser": "Chrome",
//     "Platform": process.platform,
//     "Executed": "Local"
//   }
// };

// reporter.generate(options);
